version: '3.7'

services:
    database:
        container_name: cashier-kiosk-db
        image: "postgres"
        restart: always
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"
        environment:
            POSTGRES_USER: codeus
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: cashier-kiosk
            PGDATA: /data/postgres
        volumes:
        - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
